apiVersion: v1 
kind: Service
metadata:
  name: voting2-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
  selector:
    name: voting-app-deploy
    app: demo-voting-app